import Orbit_Code as OC
import numpy as np
reload(OC)


def parseFilename(filename):
   
    parts = filename.split("=")
    args = []
    for l in range(1, len(parts)):
        num = float(parts[l].split(")")[0])
        args.append(num)
    return args
    
orbit = OC.Orbit_Calculator(4,25,.001,8,.4,7.8,0.,30.,230.) 
orbit.makeOrbit() 
orbit.saveData("/Users/LBarbano/Desktop/QP_Dump/")
lam = orbit.findLam()


#To load a qp generated by Orbit_Code, copy and paste the filepath of the desired qp file here
'''
filename = 'C:/Trapped_Orbital_Integrator/tar_master_20/qp_file_154/qp_(m=4)_(th=20)_(t=2)_(CR=8)_(eps=0.3)_(x0=7.8)_(y0=-3.31767)_(vx0=168.601)_(vy0=-156.033).txt'
a = parseFilename(filename)
orbit = Orbit_Code.Orbit_Calculator(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])
f = np.loadtxt(filename)
orbit.setqp(f)
'''
#To load a qp generated by OSG, copy and paste the filename of the desired qp file here
'''
filename = "/Users/LBarbano/Desktop/Trapped_Orbital_Integrator-master/qp_file_0/qp_(m=4)_(th=25)_(t=2)_(CR=8)_(eps=0.3)_(x0=2.34226)_(y0=-3.72566)_(vx0=202.318)_(vy0=110.064).txt"
a = parseFilename(filename)
orbit = OC.Orbit_Calculator(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])
data = np.loadtxt(filename,delimiter=" ",dtype= str).astype(float)
t = data[:,0]  #next two lines switch order of t,x,y,vx,vy to x,y,vx,vy,t
data = np.c_[data[:,1:5] ,t] 
orbit.setqp(data)   
orbit.plot(1)
'''

